import { useEffect, useState, type CSSProperties, type FormEvent, type ReactNode } from "react";
import type { DashboardSummary } from "@hedgesight/contracts";
import { Activity, Bell, Box, CircleGauge, Database, Menu, MonitorDot, Pencil, Plus, Radar, RefreshCw, Search, Server, Settings, ShieldCheck, X } from "lucide-react";

type View = "overview" | "monitoring" | "devices" | "incidents" | "workers" | "settings";
type DeviceGroup = { id: string; name: string; color: string; deviceCount: number };
type MonitoringDevice = { id: string; name: string; address: string; description: string; status: string; enabled: boolean; osName: string | null; osVersion: string | null; deviceType: string | null; vendor: string | null; model: string | null; pingCheckId: string | null; intervalSeconds: number | null; pingStatus: string | null; lastRunAt: string | null; latencyMs: number | null; packetLossPercent: number | null; history: Array<{ timestamp: string; latencyMs: number | null; status: string }>; groups: DeviceGroup[] };
type Retention = { rawDays: number; fiveMinuteDays: number; hourlyDays: number; dailyDays: number; incidentDays: number; configurationDays: number };
type StorageStatus = { databaseBytes: string; interfaceSamples: string; rollups: string; interfaces: string; configurationSnapshots: string; lastMaintenance: { finishedAt: string | null; status: string; rowsDeleted: number; rollupsWritten: number } | null };
const empty: DashboardSummary = { counts: { up: 0, down: 0, degraded: 0, unknown: 0 }, devices: [], workers: [], recentIncidents: [] };
const pageCopy: Record<View, { eyebrow: string; title: string; description: string }> = {
  overview: { eyebrow: "ACTIVE MONITORING", title: "Good morning.", description: "Here’s what’s happening across your infrastructure." },
  monitoring: { eyebrow: "LIVE STATUS", title: "Monitoring", description: "Reachability and response time across every monitored device." },
  devices: { eyebrow: "INVENTORY", title: "Devices", description: "Manage and inspect everything monitored by HedgeSight." },
  incidents: { eyebrow: "EVENTS", title: "Incidents", description: "Review active outages and recently resolved checks." },
  workers: { eyebrow: "POLLING", title: "Workers", description: "Monitor the nodes executing checks across your networks." },
  settings: { eyebrow: "CONTROL PLANE", title: "Settings", description: "Review deployment, update, and platform configuration." },
};

function relativeTime(value: string | null): string {
  if (!value) return "Never";
  const seconds = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 1000));
  if (seconds < 60) return `${seconds}s ago`;
  if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`;
  return `${Math.floor(seconds / 3600)}h ago`;
}
function StatusBadge({ status }: { status: string }) { return <span className={`badge ${status}`}><i/>{status}</span>; }
function Panel({ title, subtitle, children, className = "" }: { title: string; subtitle: string; children: ReactNode; className?: string }) {
  return <article className={`panel ${className}`}><div className="panel-heading"><div><h2>{title}</h2><p>{subtitle}</p></div></div>{children}</article>;
}
function DeviceTable({ summary, loading }: { summary: DashboardSummary; loading: boolean }) {
  return <div className="table-wrap"><table><thead><tr><th>DEVICE</th><th>ADDRESS</th><th>CHECKS</th><th>LAST RESPONSE</th><th>STATUS</th></tr></thead><tbody>
    {loading && <tr><td colSpan={5} className="empty">Loading infrastructure…</td></tr>}
    {!loading && summary.devices.length === 0 && <tr><td colSpan={5} className="empty">No devices yet. Add your first monitored device.</td></tr>}
    {summary.devices.map(device => <tr key={device.id}><td><span className="device-icon"><Server size={17}/></span><strong>{device.name}</strong></td><td className="mono">{device.address}</td><td>{device.checks}</td><td>{relativeTime(device.lastSeenAt)}</td><td><StatusBadge status={device.status}/></td></tr>)}
  </tbody></table></div>;
}
function WorkerList({ summary }: { summary: DashboardSummary }) {
  return <><div className="worker-list">{summary.workers.length === 0 && <div className="empty worker-empty">Waiting for a worker to connect…</div>}{summary.workers.map(worker => <div className="worker" key={worker.id}><span className={`worker-symbol ${worker.status}`}><Box size={18}/></span><div><strong>{worker.name}</strong><small>v{worker.version} · {relativeTime(worker.lastSeenAt)}</small></div><StatusBadge status={worker.status === "online" ? "up" : "down"}/></div>)}</div><div className="secure"><ShieldCheck size={18}/><div><strong>Outbound-only connection</strong><small>Workers never access the database directly.</small></div></div></>;
}
function IncidentList({ summary }: { summary: DashboardSummary }) {
  return summary.recentIncidents.length === 0 ? <div className="calm"><ShieldCheck/><strong>All quiet</strong><p>No incidents have been recorded.</p></div> : <div className="incident-list">{summary.recentIncidents.map(incident => <div key={incident.id}><span className={`status-dot ${incident.status === "open" ? "down" : "up"}`}/><div><strong>{incident.deviceName}</strong><p>{incident.checkName}</p></div><StatusBadge status={incident.status}/><time>{relativeTime(incident.openedAt)}</time></div>)}</div>;
}
function Sparkline({ points }: { points: MonitoringDevice["history"] }) {
  const maximum = Math.max(...points.map(point => point.latencyMs ?? 0), 1);
  if (!points.length) return <div className="sparkline empty-spark"><span>Waiting for samples</span></div>;
  return <div className="sparkline" aria-label={`${points.length} response-time samples`}>{points.map((point,index) => <i key={`${point.timestamp}-${index}`} className={point.status === "up" ? "" : "failed"} style={{ height: `${Math.max(8, ((point.latencyMs ?? 0) / maximum) * 100)}%` }} title={`${point.latencyMs?.toFixed(1) ?? "No reply"} ms`}/>)}</div>;
}

export function App() {
  const hash = window.location.hash.slice(1) as View;
  const [view, setView] = useState<View>(Object.hasOwn(pageCopy, hash) ? hash : "overview");
  const [summary, setSummary] = useState<DashboardSummary>(empty);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [dialog, setDialog] = useState(false);
  const [mobileNav, setMobileNav] = useState(false);
  const [retention, setRetention] = useState<Retention>({ rawDays: 30, fiveMinuteDays: 90, hourlyDays: 365, dailyDays: 1825, incidentDays: 730, configurationDays: 365 });
  const [storage, setStorage] = useState<StorageStatus | null>(null);
  const [retentionSaved, setRetentionSaved] = useState(false);
  const [monitoring, setMonitoring] = useState<MonitoringDevice[]>([]);
  const [groups, setGroups] = useState<DeviceGroup[]>([]);
  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");
  const [osFilter, setOsFilter] = useState("all");
  const [groupFilter, setGroupFilter] = useState("all");
  const [newGroupName, setNewGroupName] = useState("");
  const [editing, setEditing] = useState<MonitoringDevice | null>(null);

  async function refresh() { try { const [dashboardResponse,monitoringResponse,groupsResponse] = await Promise.all([fetch("/api/dashboard"),fetch("/api/monitoring"),fetch("/api/groups")]); if (!dashboardResponse.ok || !monitoringResponse.ok || !groupsResponse.ok) throw new Error("Dashboard is unavailable"); setSummary(await dashboardResponse.json()); setMonitoring(await monitoringResponse.json()); setGroups(await groupsResponse.json()); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load dashboard"); } finally { setLoading(false); } }
  useEffect(() => { void refresh(); const timer = setInterval(() => void refresh(), 10_000); return () => clearInterval(timer); }, []);
  useEffect(() => { void Promise.all([fetch("/api/retention").then(r => r.json()).then(setRetention), fetch("/api/storage/status").then(r => r.json()).then(setStorage)]); }, []);
  useEffect(() => { const onHash = () => { const next = window.location.hash.slice(1) as View; if (Object.hasOwn(pageCopy, next)) setView(next); }; window.addEventListener("hashchange", onHash); return () => window.removeEventListener("hashchange", onHash); }, []);
  function navigate(next: View) { setView(next); window.location.hash = next; setMobileNav(false); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function addDevice(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const response = await fetch("/api/devices", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: data.get("name"), address: data.get("address"), description: data.get("description"), pingIntervalSeconds: Number(data.get("pingIntervalSeconds")) }) }); if (response.ok) { setDialog(false); await refresh(); navigate("monitoring"); } }
  async function saveDevice(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!editing) return; const data = new FormData(event.currentTarget); const response = await fetch(`/api/devices/${editing.id}`, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ name:data.get("name"),address:data.get("address"),description:data.get("description"),enabled:data.get("enabled")==="on",pingIntervalSeconds:Number(data.get("pingIntervalSeconds")),osName:data.get("osName")||null,osVersion:data.get("osVersion")||null,deviceType:data.get("deviceType")||null,vendor:data.get("vendor")||null,model:data.get("model")||null,groupIds:data.getAll("groupIds") }) }); if (response.ok) { setEditing(null); await refresh(); } }
  async function createGroup() { const name=newGroupName.trim(); if (!name) return; const response=await fetch("/api/groups",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name})}); if(response.ok){setNewGroupName("");await refresh();} }
  async function saveRetention(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const response = await fetch("/api/retention", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(retention) }); if (response.ok) { setRetentionSaved(true); window.setTimeout(() => setRetentionSaved(false), 2500); } }
  async function runMaintenance() { await fetch("/api/storage/maintenance", { method: "POST" }); window.setTimeout(() => void fetch("/api/storage/status").then(r => r.json()).then(setStorage), 1000); }
  function formatBytes(value?: string) { const bytes = Number(value ?? 0); if (bytes < 1_048_576) return `${Math.round(bytes / 1024)} KB`; return `${(bytes / 1_048_576).toFixed(1)} MB`; }

  const total = Object.values(summary.counts).reduce((sum, count) => sum + count, 0);
  const healthyPercent = total ? Math.round((summary.counts.up / total) * 100) : 0;
  const openIncidents = summary.recentIncidents.filter(incident => incident.status === "open").length;
  const copy = pageCopy[view];
  const osNames = [...new Set(monitoring.map(device => device.osName).filter((value): value is string => Boolean(value)))].sort();
  const filteredMonitoring = monitoring.filter(device => { const haystack=`${device.name} ${device.address} ${device.description} ${device.osName ?? ""} ${device.vendor ?? ""} ${device.model ?? ""} ${device.groups.map(group=>group.name).join(" ")}`.toLowerCase(); return haystack.includes(search.toLowerCase()) && (statusFilter==="all" || (device.pingStatus ?? "unknown")===statusFilter) && (osFilter==="all" || device.osName===osFilter) && (groupFilter==="all" || device.groups.some(group=>group.id===groupFilter)); });
  const nav = (next: View, icon: ReactNode, label: string, count?: ReactNode) => <button className={view === next ? "active" : ""} onClick={() => navigate(next)}>{icon}{label}{count}</button>;
  const managementToolbar = <div className="management-toolbar"><label className="search-box"><Search size={16}/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search name, address, OS, model or group…"/></label><select value={statusFilter} onChange={event=>setStatusFilter(event.target.value)}><option value="all">All states</option><option value="up">Up</option><option value="down">Down</option><option value="unknown">Unknown</option></select><select value={osFilter} onChange={event=>setOsFilter(event.target.value)}><option value="all">All operating systems</option>{osNames.map(os=><option key={os}>{os}</option>)}</select><select value={groupFilter} onChange={event=>setGroupFilter(event.target.value)}><option value="all">All groups</option>{groups.map(group=><option key={group.id} value={group.id}>{group.name} ({group.deviceCount})</option>)}</select><div className="create-group"><input value={newGroupName} onChange={event=>setNewGroupName(event.target.value)} onKeyDown={event=>{if(event.key==="Enter"){event.preventDefault();void createGroup();}}} placeholder="New group"/><button onClick={()=>void createGroup()} aria-label="Create group"><Plus size={15}/></button></div><span className="result-count">{filteredMonitoring.length} of {monitoring.length}</span></div>;

  return <div className="shell">
    <aside className={mobileNav ? "sidebar open" : "sidebar"}><div className="brand"><div className="brandmark"><Radar size={24}/></div><span>Hedge<span>Sight</span></span><button className="mobile-close" onClick={() => setMobileNav(false)} aria-label="Close navigation"><X/></button></div><nav aria-label="Main navigation">
      {nav("overview", <CircleGauge/>, "Overview")}{nav("monitoring", <MonitorDot/>, "Monitoring")}{nav("devices", <Server/>, "Devices", <span className="nav-count">{total}</span>)}{nav("incidents", <Bell/>, "Incidents", <span className="nav-count alert">{openIncidents}</span>)}{nav("workers", <Box/>, "Workers")}
    </nav><div className="sidebar-bottom">{nav("settings", <Settings/>, "Settings")}<div className="system-state"><span className="pulse"/><div><strong>System operational</strong><small>Control plane online</small></div></div></div></aside>
    <main><header><button className="menu" onClick={() => setMobileNav(true)} aria-label="Open navigation"><Menu/></button><div><p className="eyebrow">{copy.eyebrow}</p><h1>{copy.title}</h1><p>{copy.description}</p></div>{(view === "overview" || view === "devices") && <button className="primary" onClick={() => setDialog(true)}><Plus size={17}/> Add device</button>}</header>{error && <div className="error">{error}. Retrying automatically.</div>}
      {view === "overview" && <><section className="stats" aria-label="Device status summary"><article className="stat hero-stat"><div className="ring" style={{ "--value": `${healthyPercent * 3.6}deg` } as CSSProperties}><span>{healthyPercent}%</span></div><div><small>OVERALL HEALTH</small><strong>{summary.counts.up} of {total} devices healthy</strong><p>Calculated from active checks</p></div></article><article className="stat"><span className="status-dot up"/><small>ONLINE</small><strong>{summary.counts.up}</strong><p>Devices responding</p></article><article className="stat"><span className="status-dot down"/><small>DOWN</small><strong>{summary.counts.down}</strong><p>Needs attention</p></article><article className="stat"><span className="status-dot unknown"/><small>UNKNOWN</small><strong>{summary.counts.unknown + summary.counts.degraded}</strong><p>Pending or degraded</p></article></section><section className="grid"><Panel title="Infrastructure" subtitle="Live device health from your polling workers" className="devices"><DeviceTable summary={summary} loading={loading}/><button className="panel-link" onClick={() => navigate("devices")}>Open device inventory</button></Panel><Panel title="Polling workers" subtitle="Probe execution nodes" className="workers"><WorkerList summary={summary}/></Panel><Panel title="Recent incidents" subtitle="Latest state changes across all checks" className="incidents"><IncidentList summary={summary}/></Panel></section></>}
      {view === "monitoring" && <section className="page-grid">{managementToolbar}<Panel title="Device monitoring" subtitle={`${monitoring.length} devices · automatically refreshed every 10 seconds`} className="full-panel"><div className="table-wrap"><table className="monitoring-table"><thead><tr><th>DEVICE</th><th>PROFILE</th><th>PING</th><th>RESPONSE HISTORY</th><th>LAST CHECK</th><th>STATUS</th><th></th></tr></thead><tbody>{loading && <tr><td colSpan={7} className="empty">Loading live monitoring…</td></tr>}{!loading && filteredMonitoring.length===0&&<tr><td colSpan={7} className="empty">No devices match these filters.</td></tr>}{!loading && filteredMonitoring.map(device => <tr key={device.id}><td><span className="device-icon"><Server size={17}/></span><span className="device-primary"><strong>{device.name}</strong><small>{device.address}</small></span></td><td><span className="profile"><strong>{[device.vendor,device.model].filter(Boolean).join(" ") || device.deviceType || "Unprofiled device"}</strong><small>{[device.osName,device.osVersion].filter(Boolean).join(" ") || "SSH profiling not yet run"}</small></span></td><td><strong className="latency">{device.latencyMs === null ? "—" : `${device.latencyMs.toFixed(1)} ms`}</strong><small className="cell-sub">every {device.intervalSeconds ?? 60}s · {device.packetLossPercent ?? 0}% loss</small></td><td><Sparkline points={device.history}/></td><td>{relativeTime(device.lastRunAt)}</td><td><StatusBadge status={device.enabled ? device.pingStatus ?? "unknown" : "disabled"}/></td><td><button className="icon-button" onClick={()=>setEditing(device)} aria-label={`Edit ${device.name}`}><Pencil size={15}/></button></td></tr>)}</tbody></table></div></Panel></section>}
      {view === "devices" && <section className="page-grid">{managementToolbar}<Panel title="Device inventory" subtitle={`${total} configured device${total === 1 ? "" : "s"}`} className="full-panel"><div className="table-wrap"><table><thead><tr><th>DEVICE</th><th>ADDRESS</th><th>OS / TYPE</th><th>GROUPS</th><th>STATUS</th><th></th></tr></thead><tbody>{filteredMonitoring.map(device=><tr key={device.id}><td><span className="device-icon"><Server size={17}/></span><strong>{device.name}</strong></td><td className="mono">{device.address}</td><td>{device.osName || device.deviceType || "Unprofiled"}</td><td><div className="group-tags">{device.groups.length?device.groups.map(group=><span key={group.id} style={{borderColor:group.color}}>{group.name}</span>):<small>Ungrouped</small>}</div></td><td><StatusBadge status={device.enabled ? device.pingStatus ?? "unknown" : "disabled"}/></td><td><button className="icon-button" onClick={()=>setEditing(device)} aria-label={`Edit ${device.name}`}><Pencil size={15}/></button></td></tr>)}</tbody></table></div></Panel></section>}
      {view === "incidents" && <section className="page-grid"><div className="summary-row"><div><span className="status-dot down"/><strong>{openIncidents}</strong><small>OPEN</small></div><div><span className="status-dot up"/><strong>{summary.recentIncidents.filter(i => i.status === "resolved").length}</strong><small>RESOLVED RECENTLY</small></div></div><Panel title="Incident history" subtitle="Open and recently resolved monitoring events" className="full-panel"><IncidentList summary={summary}/></Panel></section>}
      {view === "workers" && <section className="page-grid"><Panel title="Polling workers" subtitle={`${summary.workers.length} registered execution node${summary.workers.length === 1 ? "" : "s"}`} className="full-panel"><WorkerList summary={summary}/></Panel><div className="info-strip"><Activity/><div><strong>Worker heartbeat</strong><p>Workers are shown offline when no heartbeat has been received for 60 seconds.</p></div></div></section>}
      {view === "settings" && <section className="settings-grid"><div className="setting-card"><Database/><div><span>DATA STORE</span><h2>PostgreSQL · {formatBytes(storage?.databaseBytes)}</h2><p>{storage?.interfaces ?? 0} interfaces · {storage?.interfaceSamples ?? 0} raw samples · {storage?.rollups ?? 0} rollups</p></div><StatusBadge status="up"/></div><Panel title="Global retention policy" subtitle="Device-specific overrides inherit from these defaults" className="full-panel"><form className="retention-form" onSubmit={saveRetention}>{([ ["rawDays","Raw samples"], ["fiveMinuteDays","5-minute rollups"], ["hourlyDays","Hourly rollups"], ["dailyDays","Daily rollups"], ["incidentDays","Incidents"], ["configurationDays","Configurations"] ] as const).map(([key,label]) => <label key={key}><span>{label}</span><div><input type="number" min="1" value={retention[key]} onChange={event => setRetention({ ...retention, [key]: Number(event.target.value) })}/><small>days</small></div></label>)}<div className="retention-actions"><button type="button" className="secondary" onClick={() => void runMaintenance()}><RefreshCw size={15}/> Run maintenance</button><button className="primary">{retentionSaved ? "Saved" : "Save policy"}</button></div></form></Panel><div className="setting-card"><RefreshCw/><div><span>LAST MAINTENANCE</span><h2>{storage?.lastMaintenance?.status ?? "Not run yet"}</h2><p>{storage?.lastMaintenance?.finishedAt ? `${relativeTime(storage.lastMaintenance.finishedAt)} · ${storage.lastMaintenance.rowsDeleted} expired rows removed` : "Rollups and retention run automatically every hour."}</p></div><span className="setting-value">0.1.0-dev</span></div><div className="setting-card"><ShieldCheck/><div><span>CONFIGURATION STORAGE</span><h2>AES-256 encrypted</h2><p>{storage?.configurationSnapshots ?? 0} deduplicated snapshots stored.</p></div><StatusBadge status="up"/></div></section>}
    </main>
    {dialog && <div className="modal-backdrop" onMouseDown={() => setDialog(false)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="add-title" onMouseDown={event => event.stopPropagation()}><button className="modal-close" onClick={() => setDialog(false)} aria-label="Close"><X/></button><p className="eyebrow">DEVICE INVENTORY</p><h2 id="add-title">Add a monitored device</h2><p>A Ping availability check will start automatically.</p><form onSubmit={addDevice}><label>Name<input name="name" placeholder="Core switch 01" required autoFocus/></label><label>Address<input name="address" placeholder="10.20.0.1" required/></label><label>Ping interval<select name="pingIntervalSeconds" defaultValue="60"><option value="10">10 seconds</option><option value="30">30 seconds</option><option value="60">1 minute</option><option value="300">5 minutes</option><option value="900">15 minutes</option></select></label><label>Description<textarea name="description" placeholder="Primary distribution switch" rows={3}/></label><div className="modal-actions"><button type="button" className="secondary" onClick={() => setDialog(false)}>Cancel</button><button className="primary">Add and monitor</button></div></form></section></div>}
    {editing && <div className="modal-backdrop" onMouseDown={()=>setEditing(null)}><section className="modal wide-modal" role="dialog" aria-modal="true" onMouseDown={event=>event.stopPropagation()}><button className="modal-close" onClick={()=>setEditing(null)} aria-label="Close"><X/></button><p className="eyebrow">DEVICE MANAGEMENT</p><h2>Edit {editing.name}</h2><form className="edit-grid" onSubmit={saveDevice}><label>Name<input name="name" defaultValue={editing.name} required/></label><label>Address<input name="address" defaultValue={editing.address} required/></label><label>Ping interval<select name="pingIntervalSeconds" defaultValue={editing.intervalSeconds ?? 60}><option value="10">10 seconds</option><option value="30">30 seconds</option><option value="60">1 minute</option><option value="300">5 minutes</option><option value="900">15 minutes</option></select></label><label className="toggle-label"><input type="checkbox" name="enabled" defaultChecked={editing.enabled}/> Monitoring enabled</label><label>OS name<input name="osName" defaultValue={editing.osName ?? ""} placeholder="Linux"/></label><label>OS version<input name="osVersion" defaultValue={editing.osVersion ?? ""}/></label><label>Device type<input name="deviceType" defaultValue={editing.deviceType ?? ""} placeholder="Server"/></label><label>Vendor<input name="vendor" defaultValue={editing.vendor ?? ""}/></label><label>Model<input name="model" defaultValue={editing.model ?? ""}/></label><label className="full-field">Description<textarea name="description" defaultValue={editing.description} rows={3}/></label><fieldset className="full-field group-picker"><legend>Groups</legend>{groups.length?groups.map(group=><label key={group.id}><input type="checkbox" name="groupIds" value={group.id} defaultChecked={editing.groups.some(item=>item.id===group.id)}/><span style={{borderColor:group.color}}>{group.name}</span></label>):<small>Create a group using the toolbar first.</small>}</fieldset><div className="modal-actions full-field"><button type="button" className="secondary" onClick={()=>setEditing(null)}>Cancel</button><button className="primary">Save changes</button></div></form></section></div>}
  </div>;
}
