import { Client,type ConnectConfig } from "ssh2";

type BackupLease={id:string;jobId:string;target:string;port:number;kind:"network_script"|"server_files";script:string;paths:string[];username:string;password:string;hostKeyFingerprint:string|null};
export type BackupResult={success:boolean;message:string;contentBase64?:string};
const maximumBytes=8*1024*1024;

function quote(value:string){return `'${value.replace(/'/g,"'\\''")}'`;}
function execute(client:Client,command:string):Promise<Buffer>{return new Promise((resolve,reject)=>client.exec(command,(error,stream)=>{if(error)return reject(error);const output:Buffer[]=[];let size=0,stderr="";stream.on("data",(chunk:Buffer)=>{size+=chunk.length;if(size<=maximumBytes*1.5)output.push(chunk);}).stderr.on("data",(chunk:Buffer)=>stderr+=chunk.toString());stream.on("close",(code:number|null)=>{if(size>maximumBytes*1.5)return reject(new Error("Backup exceeded the 8 MB initial storage limit"));if(code!==0)return reject(new Error(stderr.trim()||`Remote command exited ${code}`));resolve(Buffer.concat(output));});}));}

export async function collectBackup(job:BackupLease):Promise<BackupResult>{const client=new Client();try{const config:ConnectConfig={host:job.target,port:Number(job.port||22),username:job.username,password:job.password,readyTimeout:30_000,hostHash:"sha256",hostVerifier:(fingerprint:string)=>!job.hostKeyFingerprint||fingerprint===job.hostKeyFingerprint};await new Promise<void>((resolve,reject)=>client.once("ready",resolve).once("error",reject).connect(config));let content:Buffer;if(job.kind==="network_script")content=await execute(client,job.script);else{const paths=job.paths.map(quote).join(" ");const encoded=await execute(client,`tar -czf - -- ${paths} 2>/dev/null | base64`);content=Buffer.from(encoded.toString().replace(/\s/g,""),"base64");}if(!content.length)throw new Error("Remote backup returned no data");if(content.length>maximumBytes)throw new Error("Backup exceeded the 8 MB initial storage limit");return {success:true,message:`Backup collected successfully (${content.length} bytes)`,contentBase64:content.toString("base64")};}catch(error){return {success:false,message:error instanceof Error?error.message:"Backup failed"};}finally{client.end();}}

export async function leaseBackup(apiUrl:string,token:string,workerName:string,version:string):Promise<BackupLease|null>{const response=await fetch(`${apiUrl}/api/workers/backups/lease`,{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify({name:workerName,version})});if(response.status===204)return null;if(!response.ok)throw new Error(`Backup lease failed with HTTP ${response.status}`);return response.json() as Promise<BackupLease>;}
export async function submitBackup(apiUrl:string,token:string,job:BackupLease,result:BackupResult){const response=await fetch(`${apiUrl}/api/workers/backups/${job.id}/result`,{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify(result)});if(!response.ok)throw new Error(`Backup result failed with HTTP ${response.status}`);}
