import { request } from "node:https";
import { performance } from "node:perf_hooks";
import type { ProbeJob, ProbeResult } from "@hedgesight/contracts";

const decode=(value:string)=>value.replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'");
const esc=(value:unknown)=>String(value??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;");
const text=(xml:string,tag:string)=>decode(xml.match(new RegExp(`<(?:(?:\\w+):)?${tag}[^>]*>([\\s\\S]*?)<\\/(?:(?:\\w+):)?${tag}>`))?.[1]?.replace(/<[^>]+>/g,"")??"");
const ref=(xml:string,name:string)=>xml.match(new RegExp(`<(?:(?:\\w+):)?${name}[^>]*>([^<]+)</`))?.[1]??"";
const property=(xml:string,name:string)=>{for(const block of xml.match(/<propSet>[\s\S]*?<\/propSet>/g)??[])if(text(block,"name")===name)return block.match(/<val[^>]*>([\s\S]*?)<\/val>/)?.[1]??"";return "";};
const num=(value:string)=>Number(text(`<v>${value}</v>`,"v")||0);
const envelope=(body:string)=>`<?xml version="1.0"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:vim="urn:vim25"><soapenv:Body>${body}</soapenv:Body></soapenv:Envelope>`;

class VSphereClient{
  cookie="";
  constructor(private host:string,private port:number,private verifyTls:boolean,private timeout:number){}
  call(body:string):Promise<string>{return new Promise((resolve,reject)=>{const payload=envelope(body),req=request({hostname:this.host,port:this.port,path:"/sdk",method:"POST",rejectUnauthorized:this.verifyTls,timeout:this.timeout,headers:{"content-type":"text/xml; charset=utf-8","soapaction":"urn:vim25/8.0.1.0","content-length":Buffer.byteLength(payload),cookie:this.cookie,"user-agent":"HedgeSight-Worker/0.1"}},res=>{const chunks:Buffer[]=[];const setCookie=res.headers["set-cookie"]?.[0];if(setCookie)this.cookie=setCookie.split(";")[0];res.on("data",chunk=>chunks.push(Buffer.from(chunk))).on("end",()=>{const xml=Buffer.concat(chunks).toString();if((res.statusCode??500)>=400||xml.includes("<soapenv:Fault")||xml.includes("<soap:Fault"))reject(new Error(text(xml,"faultstring")||`vSphere API returned HTTP ${res.statusCode}`));else resolve(xml);});});req.on("timeout",()=>req.destroy(new Error("vSphere API timed out"))).on("error",reject);req.end(payload);});}
}

export async function vsphere(job:ProbeJob):Promise<ProbeResult>{
  const startedAt=new Date(),started=performance.now(),client=new VSphereClient(job.target,Number(job.config.port??443),job.config.verifyTls!==false,job.timeoutMs);
  try{
    const service=await client.call(`<vim:RetrieveServiceContent><vim:_this type="ServiceInstance">ServiceInstance</vim:_this></vim:RetrieveServiceContent>`);
    const session=ref(service,"sessionManager"),search=ref(service,"searchIndex"),collector=ref(service,"propertyCollector"),viewManager=ref(service,"viewManager"),rootFolder=ref(service,"rootFolder");
    await client.call(`<vim:Login><vim:_this type="SessionManager">${esc(session)}</vim:_this><vim:userName>${esc(job.config.username)}</vim:userName><vim:password>${esc(job.config.password)}</vim:password></vim:Login>`);
    const found=await client.call(`<vim:FindByIp><vim:_this type="SearchIndex">${esc(search)}</vim:_this><vim:ip>${esc(job.target)}</vim:ip><vim:vmSearch>false</vim:vmSearch></vim:FindByIp>`);
    let hostRef=text(found,"returnval"),endpointType="esxi",managedHostCount=1;
    if(!hostRef&&viewManager&&rootFolder){endpointType="vcenter";const created=await client.call(`<vim:CreateContainerView><vim:_this type="ViewManager">${esc(viewManager)}</vim:_this><vim:container type="Folder">${esc(rootFolder)}</vim:container><vim:type>HostSystem</vim:type><vim:recursive>true</vim:recursive></vim:CreateContainerView>`),viewRef=text(created,"returnval"),inventory=await client.call(`<vim:RetrievePropertiesEx><vim:_this type="PropertyCollector">${esc(collector)}</vim:_this><vim:specSet><vim:propSet><vim:type>ContainerView</vim:type><vim:pathSet>view</vim:pathSet></vim:propSet><vim:objectSet><vim:obj type="ContainerView">${esc(viewRef)}</vim:obj></vim:objectSet></vim:specSet><vim:options/></vim:RetrievePropertiesEx>`),hosts=[...property(inventory,"view").matchAll(/<ManagedObjectReference[^>]*>([^<]+)<\/ManagedObjectReference>/g)].map(match=>match[1]);managedHostCount=hosts.length;hostRef=hosts[0]??"";void client.call(`<vim:DestroyView><vim:_this type="ContainerView">${esc(viewRef)}</vim:_this></vim:DestroyView>`).catch(()=>undefined);}
    if(!hostRef)throw new Error("No ESXi host was found at this endpoint or in its vCenter inventory");
    const paths=["name","summary.hardware.numCpuCores","summary.hardware.cpuMhz","summary.hardware.memorySize","summary.hardware.vendor","summary.hardware.model","summary.quickStats.overallCpuUsage","summary.quickStats.overallMemoryUsage","summary.quickStats.uptime","summary.overallStatus","config.product.fullName","config.product.version","config.product.build","datastore","config.network.pnic"];
    const profile=await client.call(`<vim:RetrievePropertiesEx><vim:_this type="PropertyCollector">${esc(collector)}</vim:_this><vim:specSet><vim:propSet><vim:type>HostSystem</vim:type>${paths.map(path=>`<vim:pathSet>${path}</vim:pathSet>`).join("")}</vim:propSet><vim:objectSet><vim:obj type="HostSystem">${esc(hostRef)}</vim:obj></vim:objectSet></vim:specSet><vim:options/></vim:RetrievePropertiesEx>`);
    const cores=num(property(profile,"summary.hardware.numCpuCores")),cpuMhz=num(property(profile,"summary.hardware.cpuMhz")),cpuUsedMhz=num(property(profile,"summary.quickStats.overallCpuUsage")),memoryBytes=num(property(profile,"summary.hardware.memorySize")),memoryUsedBytes=num(property(profile,"summary.quickStats.overallMemoryUsage"))*1024*1024;
    const cpuUsedPercent=cores&&cpuMhz?cpuUsedMhz/(cores*cpuMhz)*100:0,memoryUsedPercent=memoryBytes?memoryUsedBytes/memoryBytes*100:0;
    const datastoreRefs=[...property(profile,"datastore").matchAll(/<ManagedObjectReference[^>]*>([^<]+)<\/ManagedObjectReference>/g)].map(match=>match[1]);
    const datastores:Array<Record<string,unknown>>=[];
    if(datastoreRefs.length){const response=await client.call(`<vim:RetrievePropertiesEx><vim:_this type="PropertyCollector">${esc(collector)}</vim:_this><vim:specSet><vim:propSet><vim:type>Datastore</vim:type><vim:pathSet>summary.name</vim:pathSet><vim:pathSet>summary.capacity</vim:pathSet><vim:pathSet>summary.freeSpace</vim:pathSet><vim:pathSet>summary.accessible</vim:pathSet><vim:pathSet>summary.type</vim:pathSet></vim:propSet>${datastoreRefs.map(id=>`<vim:objectSet><vim:obj type="Datastore">${esc(id)}</vim:obj></vim:objectSet>`).join("")}</vim:specSet><vim:options/></vim:RetrievePropertiesEx>`);for(const object of response.match(/<objects>[\s\S]*?<\/objects>/g)??[]){const capacity=num(property(object,"summary.capacity")),freeBytes=num(property(object,"summary.freeSpace"));datastores.push({id:text(object,"obj"),name:text(`<v>${property(object,"summary.name")}</v>`,"v"),type:text(`<v>${property(object,"summary.type")}</v>`,"v"),capacityBytes:capacity,freeBytes,usedBytes:capacity-freeBytes,usedPercent:capacity?100*(capacity-freeBytes)/capacity:0,accessible:text(`<v>${property(object,"summary.accessible")}</v>`,"v")==="true"});}}
    const pnics=(property(profile,"config.network.pnic").match(/<PhysicalNic>[\s\S]*?<\/PhysicalNic>/g)??[]).map(block=>({name:text(block,"device"),driver:text(block,"driver"),macAddress:text(block,"mac"),speedMbps:Number(text(block,"speedMb")||0),linkUp:Boolean(text(block,"linkSpeed"))}));
    const selected=Array.isArray(job.config.monitoredComponents)?job.config.monitoredComponents.map(String):null,monitored=(id:string)=>selected===null||selected.includes(id),metrics:Record<string,number>={vsphereResponseTimeMs:performance.now()-started};
    if(monitored("cpu"))metrics.cpuUsedPercent=cpuUsedPercent;if(monitored("memory"))metrics.memoryUsedPercent=memoryUsedPercent;for(const datastore of datastores)if(monitored(`datastore:${datastore.id}`))metrics[`datastoreUsedPercent:${datastore.id}`]=Number(datastore.usedPercent);for(const nic of pnics)if(monitored(`interface:${nic.name}`)){metrics[`interfaceLinkUp:${nic.name}`]=nic.linkUp?1:0;metrics[`interfaceSpeedMbps:${nic.name}`]=nic.speedMbps;}
    const alerts:string[]=[];if(monitored("cpu")&&cpuUsedPercent>=Number(job.config.cpuThresholdPercent??90))alerts.push(`CPU ${cpuUsedPercent.toFixed(1)}%`);if(monitored("memory")&&memoryUsedPercent>=Number(job.config.memoryThresholdPercent??90))alerts.push(`memory ${memoryUsedPercent.toFixed(1)}%`);for(const datastore of datastores)if(monitored(`datastore:${datastore.id}`)&&Number(datastore.usedPercent)>=Number(job.config.diskThresholdPercent??90))alerts.push(`${datastore.name} ${Number(datastore.usedPercent).toFixed(1)}%`);
    void client.call(`<vim:Logout><vim:_this type="SessionManager">${esc(session)}</vim:_this></vim:Logout>`).catch(()=>undefined);
    return {status:alerts.length?"degraded":"up",startedAt:startedAt.toISOString(),finishedAt:new Date().toISOString(),latencyMs:performance.now()-started,message:alerts.length?`Resource threshold exceeded: ${alerts.join(", ")}`:`vSphere profile collected from ${text(`<v>${property(profile,"name")}</v>`,"v")}`,metrics,observations:{hostname:text(`<v>${property(profile,"name")}</v>`,"v"),osName:"VMware ESXi",osVersion:text(`<v>${property(profile,"config.product.version")}</v>`,"v"),build:text(`<v>${property(profile,"config.product.build")}</v>`,"v"),productName:text(`<v>${property(profile,"config.product.fullName")}</v>`,"v"),vendor:text(`<v>${property(profile,"summary.hardware.vendor")}</v>`,"v"),model:text(`<v>${property(profile,"summary.hardware.model")}</v>`,"v"),cpuCount:cores,cpuMhz,cpuUsedPercent,memoryBytes,memoryUsedBytes,memoryUsedPercent,uptimeSeconds:num(property(profile,"summary.quickStats.uptime")),overallStatus:text(`<v>${property(profile,"summary.overallStatus")}</v>`,"v"),datastores,interfaces:pnics}};
  }catch(error){return {status:"unknown",startedAt:startedAt.toISOString(),finishedAt:new Date().toISOString(),latencyMs:performance.now()-started,message:error instanceof Error?error.message:"vSphere profiling failed"};}
}
