import { createHash } from "node:crypto";
import express from "express";
import { z } from "zod";
import { validToken } from "./auth.js";
import { pool } from "./db.js";

export const backupRouter:express.Router=express.Router();
const uuid=z.string().uuid();
function operator(response:express.Response){if(!["admin","operator"].includes(response.locals.user?.role)){response.status(403).json({error:"Operator access required"});return false;}return true;}

backupRouter.get("/backups/summary",async(_request,response)=>{const [counts,recent]=await Promise.all([
  pool.query(`SELECT count(*)::int AS total,count(*) FILTER(WHERE enabled)::int AS enabled,count(*) FILTER(WHERE last_status='success')::int AS healthy,count(*) FILTER(WHERE last_status='failed')::int AS failed,count(*) FILTER(WHERE last_status IN ('never','queued','running'))::int AS pending FROM backup_jobs`),
  pool.query(`SELECT r.id,r.state,r.created_at AS "createdAt",r.finished_at AS "finishedAt",r.message,r.size_bytes AS "sizeBytes",j.name AS "jobName",d.name AS "deviceName",p.kind FROM backup_runs r JOIN backup_jobs j ON j.id=r.job_id JOIN devices d ON d.id=j.device_id JOIN backup_profiles p ON p.id=j.profile_id ORDER BY r.created_at DESC LIMIT 12`)
]);response.json({...counts.rows[0],recent:recent.rows});});

backupRouter.get("/backups/profiles",async(_request,response)=>{const result=await pool.query(`SELECT id,name,description,kind,script,paths,created_at AS "createdAt",updated_at AS "updatedAt",(SELECT count(*)::int FROM backup_jobs j WHERE j.profile_id=p.id) AS "jobCount" FROM backup_profiles p ORDER BY name`);response.json(result.rows);});
backupRouter.post("/backups/profiles",async(request,response)=>{if(!operator(response))return;const parsed=z.object({name:z.string().trim().min(1).max(120),description:z.string().trim().max(1000).default(""),kind:z.enum(["network_script","server_files"]),script:z.string().max(20000).default(""),paths:z.array(z.string().trim().min(1).max(1000)).max(100).default([])}).safeParse(request.body);if(!parsed.success)return response.status(400).json({error:"Enter a name and either a device script or at least one path"});const v=parsed.data;if((v.kind==="network_script"&&!v.script.trim())||(v.kind==="server_files"&&!v.paths.length))return response.status(400).json({error:"This profile has no backup content configured"});const result=await pool.query(`INSERT INTO backup_profiles(name,description,kind,script,paths,created_by_user_id) VALUES($1,$2,$3,$4,$5,$6) RETURNING id`,[v.name,v.description,v.kind,v.script,v.paths,response.locals.user.id]);response.status(201).json(result.rows[0]);});
backupRouter.delete("/backups/profiles/:id",async(request,response)=>{if(!operator(response))return;try{const result=await pool.query("DELETE FROM backup_profiles WHERE id=$1 RETURNING id",[request.params.id]);response.json({deleted:Boolean(result.rowCount)});}catch{return response.status(409).json({error:"Remove jobs using this profile first"});}});

backupRouter.get("/backups/jobs",async(_request,response)=>{const result=await pool.query(`SELECT j.id,j.name,j.interval_seconds AS "intervalSeconds",j.retention_count AS "retentionCount",j.enabled,j.next_run_at AS "nextRunAt",j.last_run_at AS "lastRunAt",j.last_status AS "lastStatus",j.last_message AS "lastMessage",j.ssh_port AS "sshPort",p.id AS "profileId",p.name AS "profileName",p.kind,d.id AS "deviceId",d.name AS "deviceName",c.id AS "credentialId",c.name AS "credentialName" FROM backup_jobs j JOIN backup_profiles p ON p.id=j.profile_id JOIN devices d ON d.id=j.device_id JOIN credentials c ON c.id=j.credential_id ORDER BY j.name`);response.json(result.rows);});
backupRouter.post("/backups/jobs",async(request,response)=>{if(!operator(response))return;const parsed=z.object({name:z.string().trim().min(1).max(120),profileId:uuid,deviceId:uuid,credentialId:uuid,sshPort:z.coerce.number().int().min(1).max(65535).default(22),intervalSeconds:z.coerce.number().int().min(300).max(31536000),retentionCount:z.coerce.number().int().min(1).max(1000).default(30),enabled:z.boolean().default(true)}).safeParse(request.body);if(!parsed.success)return response.status(400).json({error:"Complete every job field; minimum schedule is five minutes"});const v=parsed.data;const result=await pool.query(`INSERT INTO backup_jobs(name,profile_id,device_id,credential_id,ssh_port,interval_seconds,retention_count,enabled,next_run_at,created_by_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,now(),$9) RETURNING id`,[v.name,v.profileId,v.deviceId,v.credentialId,v.sshPort,v.intervalSeconds,v.retentionCount,v.enabled,response.locals.user.id]);response.status(201).json(result.rows[0]);});
backupRouter.patch("/backups/jobs/:id",async(request,response)=>{if(!operator(response))return;const parsed=z.object({enabled:z.boolean()}).safeParse(request.body);if(!parsed.success)return response.status(400).json({error:"Invalid job state"});await pool.query("UPDATE backup_jobs SET enabled=$2,next_run_at=CASE WHEN $2 THEN LEAST(next_run_at,now()) ELSE next_run_at END,updated_at=now() WHERE id=$1",[request.params.id,parsed.data.enabled]);response.json({updated:true});});
backupRouter.post("/backups/jobs/:id/run",async(request,response)=>{if(!operator(response))return;await pool.query(`INSERT INTO backup_runs(job_id) VALUES($1) ON CONFLICT DO NOTHING`,[request.params.id]);await pool.query("UPDATE backup_jobs SET last_status='queued',last_message='Manual backup queued',updated_at=now() WHERE id=$1",[request.params.id]);response.status(202).json({queued:true});});
backupRouter.delete("/backups/jobs/:id",async(request,response)=>{if(!operator(response))return;const result=await pool.query("DELETE FROM backup_jobs WHERE id=$1 RETURNING id",[request.params.id]);response.json({deleted:Boolean(result.rowCount)});});
backupRouter.get("/backups/runs/:id/download",async(request,response)=>{const key=process.env.CONFIG_ENCRYPTION_KEY;if(!key)return response.status(503).json({error:"Encryption key unavailable"});const result=await pool.query(`SELECT pgp_sym_decrypt_bytea(r.encrypted_content,$2) AS content,p.kind,j.name FROM backup_runs r JOIN backup_jobs j ON j.id=r.job_id JOIN backup_profiles p ON p.id=j.profile_id WHERE r.id=$1 AND r.state='success'`,[request.params.id,key]);if(!result.rowCount)return response.status(404).json({error:"Backup not found"});const row=result.rows[0],extension=row.kind==="server_files"?"tar.gz":"txt";response.setHeader("content-disposition",`attachment; filename="${String(row.name).replace(/[^a-z0-9_-]/gi,"-")}-${request.params.id}.${extension}"`);response.type(row.kind==="server_files"?"application/gzip":"text/plain").send(row.content);});

backupRouter.post("/workers/backups/lease",async(request,response)=>{if(!validToken(request))return response.status(401).json({error:"Invalid worker token"});const parsed=z.object({name:z.string().min(1),version:z.string().default("unknown")}).safeParse(request.body);if(!parsed.success)return response.status(400).json({error:"Invalid worker"});const key=process.env.CONFIG_ENCRYPTION_KEY??"local-development-configuration-key-change-me",client=await pool.connect();try{await client.query("BEGIN");const worker=await client.query(`INSERT INTO workers(name,token_hash,version,capabilities,last_seen_at) VALUES($1,'backup-worker',$2,ARRAY['ping','http','ssh','backup'],now()) ON CONFLICT(name) DO UPDATE SET version=$2,last_seen_at=now(),capabilities=array_append(array_remove(workers.capabilities,'backup'),'backup') RETURNING id`,[parsed.data.name,parsed.data.version]);await client.query("UPDATE backup_runs SET state='expired' WHERE state='leased' AND leased_until<now()");await client.query("UPDATE backup_runs SET state='queued',worker_id=NULL,leased_until=NULL WHERE state='expired'");const run=await client.query(`WITH candidate AS (SELECT r.id FROM backup_runs r WHERE r.state='queued' ORDER BY r.created_at FOR UPDATE SKIP LOCKED LIMIT 1) UPDATE backup_runs r SET state='leased',worker_id=$1,started_at=now(),leased_until=now()+interval '10 minutes' FROM candidate WHERE r.id=candidate.id RETURNING r.id`,[worker.rows[0].id]);if(!run.rowCount){await client.query("COMMIT");return response.status(204).send();}const detail=await client.query(`SELECT r.id,j.id AS "jobId",d.address AS target,j.ssh_port AS port,p.kind,p.script,p.paths,c.username,pgp_sym_decrypt(c.password_encrypted,$2) AS password,ssh.host_key_fingerprint AS "hostKeyFingerprint" FROM backup_runs r JOIN backup_jobs j ON j.id=r.job_id JOIN backup_profiles p ON p.id=j.profile_id JOIN devices d ON d.id=j.device_id JOIN credentials c ON c.id=j.credential_id LEFT JOIN device_ssh_credentials ssh ON ssh.device_id=d.id AND ssh.credential_id=c.id WHERE r.id=$1`,[run.rows[0].id,key]);await client.query("UPDATE backup_jobs SET last_status='running',last_message='Worker is collecting backup',last_run_at=now() WHERE id=$1",[detail.rows[0].jobId]);await client.query("COMMIT");response.json(detail.rows[0]);}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}});
backupRouter.post("/workers/backups/:id/result",async(request,response)=>{if(!validToken(request))return response.status(401).json({error:"Invalid worker token"});const parsed=z.object({success:z.boolean(),message:z.string().max(4000),contentBase64:z.string().max(12_000_000).optional()}).safeParse(request.body);if(!parsed.success)return response.status(400).json({error:"Invalid backup result"});const content=parsed.data.contentBase64?Buffer.from(parsed.data.contentBase64,"base64"):null,key=process.env.CONFIG_ENCRYPTION_KEY??"local-development-configuration-key-change-me",hash=content?createHash("sha256").update(content).digest("hex"):null,client=await pool.connect();try{await client.query("BEGIN");const run=await client.query(`UPDATE backup_runs SET state=$2,finished_at=now(),leased_until=NULL,message=$3,size_bytes=$4,content_hash=$5,encrypted_content=CASE WHEN $6::bytea IS NULL THEN NULL ELSE pgp_sym_encrypt_bytea($6,$7,'cipher-algo=aes256,compress-algo=1') END WHERE id=$1 AND state='leased' RETURNING job_id`,[request.params.id,parsed.data.success?"success":"failed",parsed.data.message,content?.length??null,hash,content,key]);if(!run.rowCount){await client.query("ROLLBACK");return response.status(409).json({error:"Backup lease expired"});}await client.query(`UPDATE backup_jobs SET last_status=$2,last_message=$3,last_run_at=now(),updated_at=now() WHERE id=$1`,[run.rows[0].job_id,parsed.data.success?"success":"failed",parsed.data.message]);await client.query(`DELETE FROM backup_runs WHERE id IN (SELECT id FROM backup_runs WHERE job_id=$1 AND state='success' ORDER BY created_at DESC OFFSET (SELECT retention_count FROM backup_jobs WHERE id=$1))`,[run.rows[0].job_id]);await client.query("COMMIT");response.json({stored:true});}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}});
