import express from "express";
import { z } from "zod";
import { validToken } from "./auth.js";
import { pool } from "./db.js";

export type LogLevel="debug"|"info"|"warn"|"error";
const weights:Record<LogLevel,number>={debug:10,info:20,warn:30,error:40};
export async function writeSystemLog(level:LogLevel,source:string,category:string,message:string,context:Record<string,unknown>={}):Promise<void>{
  const setting=await pool.query("SELECT minimum_level FROM system_log_settings WHERE id=true");const minimum=(setting.rows[0]?.minimum_level??"info") as LogLevel;if(weights[level]<weights[minimum])return;
  await pool.query("INSERT INTO system_logs(level,source,category,message,context) VALUES($1,$2,$3,$4,$5)",[level,source.slice(0,120),category.slice(0,120),message.slice(0,4000),context]);
}
export const systemLogsRouter:express.Router=express.Router();
systemLogsRouter.get("/system-logs/nodes",async(_request,response)=>{const result=await pool.query(`SELECT id,name,address FROM devices ORDER BY name`);response.json(result.rows);});
systemLogsRouter.get("/system-logs",async(request,response)=>{const parsed=z.object({level:z.enum(["all","debug","info","warn","error"]).default("all"),search:z.string().max(500).default(""),source:z.string().max(120).default(""),deviceId:z.string().max(100).default(""),from:z.string().datetime().optional(),to:z.string().datetime().optional(),groupSeconds:z.coerce.number().int().min(0).max(2592000).default(3600),limit:z.coerce.number().int().min(1).max(500).default(200)}).safeParse(request.query);if(!parsed.success)return response.status(400).json({error:"Invalid log search"});const v=parsed.data,result=await pool.query(`SELECT max(l.id) AS id,max(l.created_at) AS "createdAt",min(l.created_at) AS "firstSeenAt",l.level,l.source,l.category,l.message,(array_agg(l.context ORDER BY l.created_at DESC))[1] AS context,d.id AS "deviceId",d.name AS "deviceName",d.address AS "deviceAddress",count(*)::int AS count FROM system_logs l LEFT JOIN devices d ON d.id::text=l.context->>'deviceId' WHERE ($1='all' OR l.level=$1) AND ($2='' OR l.source=$2) AND ($3='' OR l.message ILIKE '%'||$3||'%' OR l.category ILIKE '%'||$3||'%' OR d.name ILIKE '%'||$3||'%' OR d.address ILIKE '%'||$3||'%') AND ($4='' OR d.id::text=$4) AND ($5::timestamptz IS NULL OR l.created_at >= $5) AND ($6::timestamptz IS NULL OR l.created_at <= $6) GROUP BY l.level,l.source,l.category,l.message,d.id,d.name,d.address,CASE WHEN $7=0 THEN l.id::text ELSE floor(extract(epoch FROM l.created_at)/$7)::text END ORDER BY max(l.created_at) DESC LIMIT $8`,[v.level,v.source,v.search,v.deviceId,v.from??null,v.to??null,v.groupSeconds,v.limit]);response.json(result.rows);});
systemLogsRouter.get("/settings/system-logs",async(_request,response)=>{const result=await pool.query(`SELECT minimum_level AS "minimumLevel",retention_days AS "retentionDays" FROM system_log_settings WHERE id=true`);response.json(result.rows[0]);});
systemLogsRouter.put("/settings/system-logs",async(request,response)=>{if(response.locals.user?.role!=="admin")return response.status(403).json({error:"Administrator access required"});const parsed=z.object({minimumLevel:z.enum(["debug","info","warn","error"]),retentionDays:z.number().int().min(1).max(3650)}).safeParse(request.body);if(!parsed.success)return response.status(400).json({error:"Choose a logging level and retention between 1 and 3,650 days"});await pool.query("UPDATE system_log_settings SET minimum_level=$1,retention_days=$2,updated_at=now() WHERE id=true",[parsed.data.minimumLevel,parsed.data.retentionDays]);await writeSystemLog("info","api","settings",`System logging set to ${parsed.data.minimumLevel}; retention ${parsed.data.retentionDays} days`);response.json({saved:true});});
systemLogsRouter.post("/workers/system-logs",async(request,response)=>{if(!validToken(request))return response.status(401).json({error:"Invalid worker token"});const parsed=z.object({level:z.enum(["debug","info","warn","error"]),source:z.string().min(1).max(120),category:z.string().min(1).max(120),message:z.string().min(1).max(4000),context:z.record(z.string(),z.unknown()).default({})}).safeParse(request.body);if(!parsed.success)return response.status(400).json({error:"Invalid log event"});await writeSystemLog(parsed.data.level,parsed.data.source,parsed.data.category,parsed.data.message,parsed.data.context);response.status(202).json({stored:true});});
